---
- name: copy Docker Compose files
  copy:
    src: files/{{ docker-compose.yaml config }}
    dest: /somewhere/yourproject/{{ docker-compose.yaml config  }}
  loop:
  - docker-compose.yml
  - config

# use files parameter to use multiple docker-compose.yml files
- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /root/dns
    files:
    - docker-compose.yml
